version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: epul
      POSTGRES_PASSWORD: epul123
      POSTGRES_DB: escommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U epul -d escommerce_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  web:
    build: .
    command: ["./main"]
    volumes:
      - api_volume:/usr/src/app/
      - go_cache:/go/pkg/mod
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: epul
      DB_PASSWORD: epul123
      DB_NAME: escommerce_db
      DB_PORT: 5432

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_volume:/usr/src/jenkins_home:/var/jenkins_home"
    networks:
      - main-serv-bridge

networks:
  main-serv-bridge:
    driver: bridge

volumes:
  postgres_data:
  jenkins_volume:
  api_volume:
  go_cache:
