// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/muhammadsaefulr/escommerce/internal/infras/controller"
	"github.com/muhammadsaefulr/escommerce/internal/infras/repository"
	"github.com/muhammadsaefulr/escommerce/internal/infras/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserController(db *gorm.DB) *controller.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitProductController(db *gorm.DB) *controller.ProductController {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controller.NewProductController(productService)
	return productController
}
